sudo: required
dist: trusty
language: node_js
node_js:
  "node"
before_script:
  - npm install --save-dev coveralls codeclimate-test-reporter
script:
  - npm run test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < ./coverage/lcov.info
